import cv2
img =cv2.imread('/home/rukesh/recommendation/source/myrecommendationsystem/static/images/logo.jpg')
width=int(50)
height=int(50)
dimension=(width,height)
resized=cv2.resize(img,dimension,interpolation=cv2.INTER_AREA)
print(resized.shape)
cv2.imshow('output',resized)
cv2.imwrite('/home/rukesh/recommendation/source/myrecommendationsystem/static/images/logoresize.jpg',resized)
cv2.waitKey(0)
cv2.destroyAllWindows()
